basePath: /api/v1
host: localhost:3000
info:
  contact: {}
  description: This is a sample server for using Swagger with Echo.
  title: Swagger Example API
  version: "1.0"
paths:
  /api/v1/pets/{id}:
    get:
      description: Gets a pet using the pet ID
      operationId: get-pet-by-id
      parameters:
      - description: Pet ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "405":
          description: Method Not Allowed
          schema: {}
      summary: Get pet by ID
      tags:
      - Pets
swagger: "2.0"
