version: '3'

services:
  api: 
    build: .
    ports: 
      - "3000:3000"
    volumes: 
      - ./:/app
      - ./vendor:/app/vendor
    depends_on:
      - postgres

  postgres:
    build: ./internal/db
    ports:
      - 5432:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=easynight
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

volumes:
  postgres_db: